import { Actuary, Permission } from "@/types/bank_user/actuary.ts";

export const actuariesMock: Actuary[] = [
  {
    id: "a1",
    employeeId: "5817c260-e4a9-4dc1-87d9-2fa12af157d9",
    email: "employee1@gmail.com",
    username: "employee1",
    firstName: "John",
    lastName: "Smith",
    actuaryType: Permission.Supervisor,
    limit: 0,
    usedLimit: 0,
    needsApproval: false,
  },
  {
    id: "a2",
    employeeId: "3d9bd4c3-a467-4676-ac4b-2b392e7315fa",
    email: "employee2@bankapp.com",
    username: "maria.jones",
    firstName: "Maria",
    lastName: "Jones",
    actuaryType: Permission.Agent,
    limit: 150000,
    usedLimit: 25000,
    needsApproval: true,
  },
  {
    id: "a3",
    employeeId: "5d3fca51-26f2-49eb-904d-199f00d71645",
    email: "employee4@gmail.com",
    username: "ana.markovic",
    firstName: "Ana",
    lastName: "Marković",
    actuaryType: Permission.Agent,
    limit: 100000,
    usedLimit: 100000,
    needsApproval: false,
  },
  {
    id: "a4",
    employeeId: "ffff810e-b416-4b21-88f0-c565ca770192",
    email: "employee3@bankapp.com",
    username: "employee3",
    firstName: "Stefan",
    lastName: "Nikolic",
    actuaryType: Permission.Supervisor,
    limit: 0,
    usedLimit: 0,
    needsApproval: false,
  },
  {
    id: "a5",
    employeeId: "c6f44133-08f2-4a43-bd65-9cfb6b13fa5b",
    email: "admin@gmail.com",
    username: "admin",
    firstName: "Admin",
    lastName: "Admin",
    actuaryType: Permission.Supervisor, // admin je uvek supervisor
    limit: 0,
    usedLimit: 0,
    needsApproval: false,
  },
];
